"""Build the public preview from the local UI, without loading private job data.

Run with --check in CI to detect stale generated assets. Standard library only.
"""
from __future__ import annotations

import argparse
import re
import sys
import json
import hashlib
from privacy_check import APPROVED_PUBLIC_ASSETS
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src'))
from offline_studio.ui import render_workbench
from offline_studio.config import DEFAULTS
WEB = ROOT / 'src/offline_studio/web'
COMFY_REVISION = json.loads((ROOT / 'integrations.lock.json').read_text(encoding='utf-8'))['comfyui']['commit']
COMFY_ROOT = ROOT / 'integrations' / ('comfyui-' + COMFY_REVISION[:12])
COMFY_WEB = COMFY_ROOT / 'src/comfyui_py_workflow/web'
PREVIEW = ROOT / 'preview-src'
DOCS = ROOT / "docs"
PUBLIC_MEDIA = [f'bicycle-frame-{index:04d}.png' for index in range(1, 4)] + ['bicycle-final-10s.mp4']


def story_preview_stages(html: str) -> str:
    """Expose all three stages only in the public demonstration UI."""
    tabs = '<div class="workflow-strip" role="tablist" aria-label="故事视频演示阶段">'
    for key, label in [('input', '1　输入故事'), ('plan', '2　分析与分镜'), ('output', '3　生成与导出')]:
        selected = key == 'input'
        tabs += (f'<button id="story-tab-{key}" type="button" role="tab" data-story-stage="{key}" '
                 f'aria-controls="story-stage-{key}" aria-selected="{str(selected).lower()}" '
                 f'tabindex="{0 if selected else -1}" class="{"active" if selected else ""}">{label}</button>')
    tabs += '</div><p class="hint preview-stage-hint">展示模式 · 三个阶段均可直接查看，无需创建任务。</p>'
    def panel(key: str) -> str:
        return (f'<div id="story-stage-{key}" role="tabpanel" aria-labelledby="story-tab-{key}" '
                f'tabindex="0" class="{"hidden" if key != "input" else ""}">')
    replacements = [
        ('<div class="workflow-strip"><span class="active">1　输入故事</span><span>2　分析与分镜</span><span>3　生成与导出</span></div>', tabs + panel('input')),
        ('<section class="panel hidden" id="analysis-panel">', '</div>' + panel('plan') + '<section class="panel" id="analysis-panel">'),
        ('<section class="panel hidden" id="plan-panel">', '<section class="panel" id="plan-panel">'),
        ('<section class="panel hidden" id="progress-panel">', '</div>' + panel('output') + '<section class="panel" id="progress-panel">'),
        ('<section class="panel hidden" id="results-panel">', '<section class="panel" id="results-panel">'),
        ('    <div id="view-comic" class="hidden">', '    </div>\n    <div id="view-comic" class="hidden">'),
        ('<div id="analysis-empty" class="empty-state">', '<div id="analysis-empty" class="empty-state hidden">'),
        ('<div id="analysis-result" class="hidden">', '<div id="analysis-result">'),
    ]
    for before, after in replacements:
        if html.count(before) != 1:
            raise ValueError('Local story markup changed; update preview stage grouping: ' + before)
        html = html.replace(before, after, 1)
    html = re.sub(r'(<section class="panel" id="plan-panel">.*?)(<p class="hint">.*?</p>)',
                  r'\1<p class="hint">下方是公开虚构故事的分镜摘要。实际运行时，此处显示可审阅和修改的模型专用提示词与完整执行计划。</p>',
                  html, count=1, flags=re.DOTALL)
    video = '''<p class="hint">以下是仓库已有的 10 秒单车公开样片，用于演示结果播放与下载；它与上方虚构故事的 30 秒分镜独立，不是该分镜的生成结果。</p>
      <video controls preload="none" poster="assets/bicycle-frame-0001.png" aria-label="公开单车示例视频"><source src="assets/bicycle-final-10s.mp4" type="video/mp4">浏览器不支持视频播放，请下载 MP4 查看。</video>
      <p><a class="preview-download" href="assets/bicycle-final-10s.mp4" download>下载公开样片 · MP4 / 10 秒 ↓</a></p>'''
    html = html.replace('<div id="final-video"></div>', '<div id="final-video">' + video + '</div>')
    gallery = ''.join(f'<a href="assets/{name}" target="_blank" rel="noopener"><img loading="lazy" src="assets/{name}" alt="公开单车示例关键帧 {index}"></a>'
                      for index, name in enumerate(PUBLIC_MEDIA[:3], 1))
    html = html.replace('<div id="keyframe-gallery" class="gallery"></div>', '<div id="keyframe-gallery" class="gallery">' + gallery + '</div>')
    html = html.replace('<div id="clip-list" class="clip-list"></div>', '<div id="clip-list" class="clip-list"><p class="hint">本地运行后，此处列出逐段生成的视频。本预览提供上方合成样片供查看。</p></div>')
    return html


def preview_html() -> str:
    html = render_workbench(DEFAULTS, COMFY_WEB)
    html = html.replace("<!doctype html>", "<!doctype html>\n<!-- Generated by scripts/build_ui_preview.py; edit the local UI or preview sources. -->")
    html = html.replace('<link rel="stylesheet" href="/static/style.css">', '''<meta name="description" content="Offline Studio 统一工作台预览：故事漫画、故事视频、批量图片编辑与本机服务设置。使用公开示例，无上传或模型请求。">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; media-src 'self'; connect-src 'none'; form-action 'none'; base-uri 'none'">
  <link rel="stylesheet" href="style.css">
  <link rel="stylesheet" href="preview.css">''')
    html = html.replace('<body>', '''<body>
  <div class="preview-notice"><strong>界面预览</strong><span>虚构示例 · 无上传、模型或后台连接</span><a href="https://github.com/marsguo2049/offline-studio#start-on-windows">在本机运行 ↗</a></div>
  <noscript><p class="no-script">请启用 JavaScript 切换工作区。下面展示故事视频界面；真正处理任务请在本机运行项目。</p></noscript>''')
    html = re.sub(r'<script\b[^>]*>.*?</script>\s*', '', html, flags=re.DOTALL)
    html = html.replace('</body>', '  <script src="preview.js"></script>\n</body>')
    html = html.replace('href="/studio-assets/studio.css"', 'href="studio.css"')
    html = html.replace('href="/translate"', 'href="translate.html"')
    html = story_preview_stages(html)
    # Disable real action controls in the HTML itself, even when scripts are off.
    html = re.sub(r'<(input|textarea|select)\b', r'<\1 disabled', html)
    def disable_action(match: re.Match[str]) -> str:
        tag = match.group(0)
        return tag if 'data-view=' in tag or 'data-story-stage=' in tag or 'id="go-settings"' in tag else tag.replace('<button', '<button disabled', 1)
    html = re.sub(r'<button\b[^>]*>', disable_action, html)
    html = html.replace('<span id="service-summary">检测中</span>', '<span id="service-summary">仅展示</span>')
    html = html.replace('在本机处理与保存<small>', '公开虚构示例<small>')
    html = html.replace('创作留在本机。</span>', '静态预览 · 实际任务请在本机运行。</span>')
    html = html.replace('<select disabled id="batch-tool"', '<select id="batch-tool"')
    return html


def overview_svg() -> str:
    """A code-native UI overview, explicitly labelled as an illustration."""
    parts = ['<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="960" viewBox="0 0 1440 960" role="img" aria-labelledby="title desc">',
             '<title id="title">Offline Studio unified workspace overview</title>',
             '<desc id="desc">Light workspace with Story video, Story comic, Batch tools and Service settings navigation. The batch view shows sample files, a shared prompt, progress and history. UI illustration with fictional examples, not a live job.</desc>',
             '<style>text { font-family: "Segoe UI", "Microsoft YaHei", "Noto Sans CJK SC", sans-serif; } .muted { fill: #707887; }</style>']
    def rect(x, y, w, h, fill='#ffffff', stroke='none', radius=0):
        parts.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{radius}" fill="{fill}" stroke="{stroke}"/>')
    def text(x, y, value, size=16, color='#202733', weight=400):
        parts.append(f'<text x="{x}" y="{y}" font-size="{size}" fill="{color}" font-weight="{weight}">{escape(value)}</text>')
    def line(x1, y1, x2, y2):
        parts.append(f'<path d="M{x1} {y1}H{x2}" stroke="#e3e6ec"/>')
    rect(0, 0, 1440, 960, '#f7f8fa')
    rect(0, 0, 1440, 44, '#eef0ff')
    text(26, 28, 'OFFLINE STUDIO', 13, '#525ce5', 700)
    text(225, 28, '界面概览 · 公开虚构示例', 13, '#707887')
    text(1070, 28, '本地创作 / 批量处理 / 统一入口', 13, '#525ce5')
    rect(0, 44, 224, 916)
    rect(22, 76, 36, 36, '#525ce5', radius=11)
    text(30, 104, 'O', 27, '#ffffff')
    text(70, 92, 'Offline Studio', 18, weight=700)
    text(70, 113, '本地创作工作台', 12, '#707887')
    text(30, 170, '工作区', 13, '#9299a7')
    text(35, 216, '01', 14, '#9299a7'); text(72, 216, '故事视频', 16, '#707887')
    text(35, 267, '02', 14, '#9299a7'); text(72, 267, '故事漫画', 16, '#707887')
    rect(16, 288, 192, 48, '#eef0ff', radius=8)
    text(35, 319, '03', 14, '#525ce5'); text(72, 319, '批量工具', 16, '#525ce5', 650)
    text(35, 371, '04', 14, '#9299a7'); text(72, 371, '服务设置', 16, '#707887')
    text(28, 897, '● 在本机处理与保存', 13, '#707887')
    text(28, 923, 'ComfyUI Py Workflow', 12, '#9299a7')
    text(264, 92, 'BATCH TOOLS', 12, '#9299a7', 600)
    text(264, 140, '一次设定，批量完成。', 34, weight=700)
    text(264, 173, '重复的图片处理，交给本地工作流。', 15, '#707887')
    rect(1210, 104, 190, 36, '#ffffff', '#e3e6ec', 18)
    text(1227, 127, '● 本机服务 · 仅展示', 13, '#707887')
    text(264, 213, '选择批量工具', 12, '#707887')
    rect(264, 225, 224, 42, '#ffffff', '#e3e6ec', 8)
    text(280, 253, '批量图片编辑', 16, weight=600); text(459, 252, '⌄', 16, '#707887')
    text(508, 252, '用同一段提示词，逐张修改图片。', 14, '#707887')
    rect(1190, 228, 210, 30, '#eef0f5', radius=5)
    text(1203, 249, 'Qwen Image Edit 2509', 13, '#707887')
    rect(264, 291, 754, 518, '#ffffff', '#e3e6ec', 12)
    text(288, 331, '图片与修改要求', 19, weight=650)
    rect(905, 307, 90, 34, '#ffffff', '#e3e6ec', 7); text(920, 329, '新建任务', 13, '#707887')
    rect(288, 358, 706, 158, '#fafbff', '#cdd1e7', 10)
    text(624, 395, '＋', 30, '#737be8')
    text(574, 425, '把图片放到这里', 17, weight=600)
    text(482, 452, '拖入图片，或选择多个文件 / 整个文件夹', 14, '#707887')
    rect(516, 467, 115, 34, '#eef0ff', '#dfe2fa', 7); text(542, 490, '选择图片', 14, '#525ce5')
    rect(643, 467, 128, 34, '#ffffff', '#e3e6ec', 7); text(669, 490, '选择文件夹', 14, '#707887')
    text(288, 545, '已添加 3 张图片 · 示例', 13, '#707887'); text(962, 545, '清空', 13, '#707887')
    text(288, 574, 'product-front.png     product-side.png     product-detail.png', 13, '#707887')
    text(288, 612, '想如何修改？', 16, weight=600)
    rect(288, 627, 706, 70, '#ffffff', '#e3e6ec', 8)
    text(304, 655, '把背景换成浅灰色摄影棚，保留主体和自然阴影。', 15, '#707887')
    text(288, 727, '›  高级参数', 14); text(397, 727, '负向提示词、种子、超时与工作流', 13, '#9299a7')
    line(288, 745, 994, 745)
    text(288, 783, '仅需 ComfyUI，无需启动 LM Studio。', 13, '#9299a7')
    rect(813, 759, 181, 34, '#525ce5', radius=7); text(836, 782, '开始批量处理 →', 14, '#ffffff', 600)
    rect(1038, 291, 362, 230, '#ffffff', '#e3e6ec', 12)
    text(1062, 330, '当前任务', 17, weight=650)
    rect(1324, 308, 52, 26, '#f1f3f7', radius=5); text(1332, 326, '待开始', 12, '#707887')
    text(1062, 372, '添加图片和修改要求，开始第一批处理。', 13, '#707887')
    rect(1062, 399, 314, 6, '#eff0f6', radius=3)
    for x, value, label in [(1062, '0/3', '已处理'), (1180, '0', '成功'), (1297, '0', '失败')]:
        text(x, 453, value, 27, weight=600); text(x, 481, label, 13, '#9299a7')
    rect(1038, 541, 362, 202, '#ffffff', '#e3e6ec', 12)
    text(1062, 579, '最近任务', 17, weight=650); text(1347, 579, '刷新', 13, '#707887')
    line(1062, 599, 1376, 599)
    text(1062, 630, '图片编辑 · 示例任务', 14)
    text(1062, 657, '统一商品图背景 · 3 张图片', 13, '#9299a7')
    text(1062, 713, '任务历史与处理结果集中查看', 13, '#707887')
    text(1046, 777, '任务和结果保存在本机。', 13, '#9299a7')
    text(1046, 802, '关闭页面后，也可以回来继续查看。', 13, '#9299a7')
    rect(264, 829, 1136, 90, '#ffffff', '#e3e6ec', 12)
    text(288, 866, '处理结果', 17, weight=650)
    text(460, 866, '每完成一张，自动更新一张。', 14, '#9299a7')
    text(288, 894, '查看原图 / 下载结果 / 打开任务文件夹', 13, '#707887')
    text(264, 945, 'OFFLINE STUDIO · 创作 / 翻译 / 本地服务', 11, '#a6adba'); text(1190, 945, '界面示意 · 非真实任务', 12, '#9299a7')
    parts.append('</svg>')
    return '\n'.join(parts) + '\n'


def translation_preview() -> str:
    page = (WEB / 'translate.html').read_text(encoding='utf-8')
    page = page.replace('<head>', "<head><meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; style-src 'self'; img-src 'self' data:; connect-src 'none'; form-action 'none'; base-uri 'none'\">")
    page = page.replace('/static/style.css', 'style.css').replace('/studio-assets/studio.css', 'studio.css')
    page = re.sub(r'<script[^>]*>.*?</script>', '', page, flags=re.DOTALL)
    page = page.replace('href="/#', 'href="index.html#').replace('href="/translate"', 'href="translate.html"')
    page = re.sub(r'<(input|button)\b', r'<\1 disabled', page)
    page = page.replace('文档上传到本机工作台，原文件保持不变。', '公开虚构示例 · 静态预览，不上传文件、不连接本机服务。')
    page = page.replace('选择或创建一个任务', '旅行札记.docx · 虚构示例')
    page = page.replace('尚未选择</span>', '展示模式</span>')
    page = page.replace('正在读取本机设置…', '本地文字模型（示例，未连接服务）')
    page = page.replace('操作开始后，这里会显示进度。', '检查文档 → 提取术语 → 翻译 / 继续 → 导出中文与中英对照。\n这里展示流程，不是真实翻译结果。')
    return page


def main() -> None:
    global COMFY_ROOT, COMFY_WEB
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--comfy-root', type=Path, default=COMFY_ROOT)
    args = parser.parse_args()
    COMFY_ROOT = args.comfy_root.resolve()
    COMFY_WEB = COMFY_ROOT / 'src/comfyui_py_workflow/web'
    artifacts = {
        DOCS / 'index.html': preview_html(),
        DOCS / 'translate.html': translation_preview(),
        DOCS / 'style.css': (COMFY_WEB / 'style.css').read_text(encoding='utf-8'),
        DOCS / 'studio.css': (WEB / 'studio.css').read_text(encoding='utf-8'),
        DOCS / 'preview.js': (PREVIEW / 'preview.js').read_text(encoding='utf-8'),
        DOCS / 'preview.css': (PREVIEW / 'preview.css').read_text(encoding='utf-8'),
        DOCS / 'assets/offline-studio-preview.svg': overview_svg(),
    }
    public_assets = {}
    for name in PUBLIC_MEDIA:
        data = (COMFY_ROOT / 'examples/bicycle-sequence/assets' / name).read_bytes()
        if hashlib.sha256(data).hexdigest() != APPROVED_PUBLIC_ASSETS['docs/assets/' + name]:
            raise ValueError('Public example differs from reviewed published media: ' + name)
        artifacts[DOCS / 'assets' / name] = data
        public_assets['docs/assets/' + name] = hashlib.sha256(data).hexdigest()
    artifacts[DOCS / 'public-assets.json'] = json.dumps(public_assets, indent=2) + '\n'
    stale = []
    for path, content in artifacts.items():
        expected = content if isinstance(content, bytes) else content.encode('utf-8')
        if args.check:
            actual = path.read_bytes() if path.exists() else None
            if isinstance(content, str) and actual is not None:
                actual = actual.replace(b'\r\n', b'\n')
            if actual != expected:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)
    if stale:
        parser.exit(1, 'Stale preview: ' + ', '.join(stale) + '\n')
    print('Offline Studio preview is up to date.' if args.check else 'Built Offline Studio preview.')


if __name__ == '__main__':
    main()
